### ISSUE TITLE
Add `padauk` topic to the repository

### ISSUE THREAD

**Issue by cmfcmf** [AndersBNielsen/pms150c-projects#2]
Hi @AndersBNielsen!

We have recently updated the https://free-pdk.github.io/ website to automatically search GitHub for Padauk µC-related projects. In case you don't know, Free PDK is an effort to create an open source toolchain for Padauk µCs.
It would great if you added the `padauk` topic to this repository [as explained here](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository), so that this repository shows up in the list of projects from the community at https://free-pdk.github.io/#projects-from-the-community.
Tha makes it easier for others to find this repository and grow our open source Padauk ecosystem. :100:

**Comment by AndersBNielsen** [comment]
Sure! 👍
